import { Flex } from "@chakra-ui/react"
import Head from "next/head"
import { ReactElement } from "react"

const DashboardLayout = ({ children, title }: { children: ReactElement, title: string }) => {
    console.log(title);
    return (
        <Flex>
            <Head>
                <title>Klug | {title}</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            {children}
        </Flex>
    )
}
export default DashboardLayout